using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using TaskFlow.Wasm;
using TaskFlow.Wasm.Services;
var builder=WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");
builder.Services.AddScoped(sp=>new HttpClient());
builder.Services.AddScoped<GoogleAuthService>();
builder.Services.AddScoped<GoogleDriveService>();
await builder.Build().RunAsync();